apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: zcorrecteurs-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: technique@corrigraphie.org
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik