---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zcorrecteurs
  namespace: zcorrecteurs-prod
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: zcorrecteurs-prod-redirect-https@kubernetescrd,zcorrecteurs-prod-redirect-www@kubernetescrd
spec:
  rules:
  - host: zcorrecteurs.fr
    http:
      paths:
      - backend:
          serviceName: zcorrecteurs
          servicePort: 80
  - host: www.zcorrecteurs.fr
    http:
      paths:
      - backend:
          serviceName: zcorrecteurs
          servicePort: 80
  tls:
  - hosts:
    - zcorrecteurs.fr
    - www.zcorrecteurs.fr
    secretName: traefik-cert
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: zcorrecteurs-prod
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-www
  namespace: zcorrecteurs-prod
spec:
  redirectRegex:
    regex: ^http(s?)://zcorrecteurs.fr/(.*)
    replacement: http${1}://www.zcorrecteurs.fr/${2}
    permanent: true