---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sphinx
  namespace: zcorrecteurs-prod
  labels:
    app: sphinx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sphinx
  template:
    metadata:
      labels:
        app: sphinx
    spec:
      containers:
      - name: server
        image: docker.pkg.github.com/zcorrecteurs/zcorrecteurs/sphinx:c7e27be39ba8368d5e779b653dc29d300b01b424
        env:
        - name: DATABASE_HOST
          value: sqlcorrigraphie.mysql.database.azure.com
        - name: DATABASE_BASE
          value: zco_prod
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: sphinx
  namespace: zcorrecteurs-prod
spec:
  selector:
    app: sphinx
  ports:
  - name: search
    protocol: TCP
    port: 5000
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hourly-cron
  namespace: zcorrecteurs-prod
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: docker.pkg.github.com/zcorrecteurs/zcorrecteurs/sphinx:c7e27be39ba8368d5e779b653dc29d300b01b424
            args:
            - reindex
            env:
            - name: DATABASE_HOST
              value: sqlcorrigraphie.mysql.database.azure.com
            - name: DATABASE_BASE
              value: zco_prod
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
          restartPolicy: Never
