---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: zcorrecteurs-prod
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: server
        image: docker.pkg.github.com/zcorrecteurs/zcorrecteurs/webserver:de4c6ed9231e96e8522b6c4c007a10df7a4b03df
        env:
        - name: DATABASE_HOST
          value: sqlcorrigraphie.mysql.database.azure.com
        - name: DATABASE_BASE
          value: zco_prod
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: sendgrid
              key: apiKey
        - name: AZURE_BLOB_DSN
          valueFrom:
            secretKeyRef:
              name: blob
              key: connectionString
        - name: SPHINX_HOST
          value: sphinx
        - name: SENTRY_DSN
          value: https://2515611307de4eb6ab651f6846988ee0@sentry.io/1359364
        - name: SENTRY_ENVIRONMENT
          value: prod
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: zcorrecteurs
  namespace: zcorrecteurs-prod
spec:
  selector:
    app: webserver
  ports:
  - name: http
    protocol: TCP
    port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zcorrecteurs
  namespace: zcorrecteurs-prod
spec:
  rules:
  - host: zcorrecteurs-prod.lb.corrigraphie.net
    http:
      paths:
      - backend:
          serviceName: zcorrecteurs
          servicePort: 80
  - host: zcorrecteurs.fr
    http:
      paths:
      - backend:
          serviceName: zcorrecteurs
          servicePort: 80
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hourly-cron
  namespace: zcorrecteurs-prod
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: docker.pkg.github.com/zcorrecteurs/zcorrecteurs/webserver:de4c6ed9231e96e8522b6c4c007a10df7a4b03df
            args:
            - console
            - zco:cron
            - --hourly
            env:
            - name: DATABASE_HOST
              value: sqlcorrigraphie.mysql.database.azure.com
            - name: DATABASE_BASE
              value: zco_prod
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sendgrid
                  key: apiKey
            - name: AZURE_BLOB_DSN
              valueFrom:
                secretKeyRef:
                  name: blob
                  key: connectionString
            - name: SPHINX_HOST
              value: sphinx
            - name: SENTRY_DSN
              value: https://2515611307de4eb6ab651f6846988ee0@sentry.io/1359364
            - name: SENTRY_ENVIRONMENT
              value: prod
          restartPolicy: Never
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: daily-cron
  namespace: zcorrecteurs-prod
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: console
            image: docker.pkg.github.com/zcorrecteurs/zcorrecteurs/webserver:de4c6ed9231e96e8522b6c4c007a10df7a4b03df
            args:
            - console
            - zco:cron
            - --daily
            env:
            - name: DATABASE_HOST
              value: sqlcorrigraphie.mysql.database.azure.com
            - name: DATABASE_BASE
              value: zco_prod
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sendgrid
                  key: apiKey
            - name: AZURE_BLOB_DSN
              valueFrom:
                secretKeyRef:
                  name: blob
                  key: connectionString
            - name: SPHINX_HOST
              value: sphinx
            - name: SENTRY_DSN
              value: https://2515611307de4eb6ab651f6846988ee0@sentry.io/1359364
            - name: SENTRY_ENVIRONMENT
              value: prod
          restartPolicy: Never
