---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sphinx
  namespace: zcorrecteurs-qa
  labels:
    app: sphinx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sphinx
  template:
    metadata:
      labels:
        app: sphinx
    spec:
      containers:
      - name: server
        image: docker.pkg.github.com/zcorrecteurs/zcorrecteurs/sphinx:98294c1c2fb821e877ea38d94455033c0f86f1f0
        env:
        - name: DATABASE_HOST
          value: sqlcorrigraphie.mysql.database.azure.com
        - name: DATABASE_BASE
          value: zco_dev
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: sphinx
  namespace: zcorrecteurs-qa
spec:
  selector:
    app: sphinx
  ports:
  - name: search
    protocol: TCP
    port: 5000
